In [18]:
import pandas as pd

# could not get geocoder workihg, pulled data from csv file instead
url='https://cocl.us/Geospatial_data/Geospatial_Coordinates.csv'
df_geo=pd.read_csv(url)
display(df_geo.head())

#Part 1 CSV was saved with an unnamed index, causing a new column "Unnamed:0" to appear. Fixed by indicating index_col=[0]
df= pd.read_csv('Week3_Capstone_part1.csv',index_col=[0])
display(df.head())

df_merged = pd.merge(df,df_geo, on = 'Postal Code')
df_merged.head(11)

print('the merged dataset has',df_merged.shape[0], 'rows and', df_merged.shape[1], 'columns')

#Save csv for use in part 3 

df_merged.to_csv('Week3_Capstone_part2.csv',index=False)

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

  Postal Code           Borough                      Neighborhood
0         M3A        North York                         Parkwoods
1         M4A        North York                  Victoria Village
2         M5A  Downtown Toronto         Regent Park, Harbourfront
3         M6A        North York  Lawrence Manor, Lawrence Heights
4         M7A      Queen's Park     Ontario Provincial Government

the merged dataset has 103 rows and 5 columns